version: '3.8'

services:
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root #These variables, used in conjunction, 
      MONGO_INITDB_ROOT_PASSWORD: example #create a new user and set that user's password. 
                                           #This user is created in the admin authentication database 
                                           #and given the role of root, which is a "superuser" role.
      MONGO_INITDB_DATABASE: the_database  #This will tell MongoDB to create a database with that name
    volumes: 
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js #FILE-IN-HOST:FILE-IN-CONTAINER
      - ./mongo_data:/data/db #=bind mount: creates a directory called mongo_data to your local filesystem and map it into the container as /data/db
      
      #- mongo_data:/data/db #=named volume: does the same as a bind mount but the location is managed by Docker
#volumes:
  #mongo_data: